### ISSUE TITLE
Wish: Add number of page.

### ISSUE THREAD

**Issue by Denisov21** [Liongold/brackets-pdfexport#13]
Hi @sbruchmann,
I would like to add a checkbox to enable or disable the creation of page numbers at the bottom center of the sheet.

**Comment by Liongold** [comment]
@Denisov21 Any information?

**Comment by Denisov21** [comment]
hi, @Liongold I am a beginner do not know the javascript.

**Comment by Liongold** [comment]
If you still want to help, I can give you some pointers.

On Sunday, April 5, 2015, Denis R <notifications@github.com> wrote:

> hi, @Liongold <https://github.com/Liongold> I am a beginner do not know
> the javascript.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Liongold/brackets-pdfexport/issues/13#issuecomment-89794308>
> .
>


-- 
Sincerely,
Jean Spiteri.

**Comment by Liongold** [comment]
@Denisov21 If you don't think you can manage to implement this feature, you can do something else or help with testing, don't worry.

**Comment by Liongold** [comment]
I'll proceed in assigning this issue to me. Sorry but this has taken long enough. However, @Denisov21 if you still want to be involved, just tell me and we'll see what can be done.

**Comment by Denisov21** [comment]
Hi @Liongold ,
Sorry for the delay in the response. Yes, I will help you with testing!!

**Comment by Liongold** [comment]
@Denisov21 Thank you very much.

**Comment by Liongold** [comment]
@Denisov21 Excuse me for the delay in getting to you back on this. I have built this feature. Its code can be found in branch 'issue-#13' of this repo. Do you mind testing it? I won't merge it for now since I need to make it more clean and readable but the code itself should work well. If you encounter any issues, please tell me. Thanks.

**Comment by Denisov21** [comment]
OK @Liongold. Soon I will test the application. Good work!

**Comment by Liongold** [comment]
@Denisov21 Did you do anything on this?

**Comment by Denisov21** [comment]
Great work! Good as I wanted it

**Comment by Liongold** [comment]
@Denisov21 Great. I'll proceed in merging the pull request. However, I won't close this issue for now because I still have identified an issue with that feature. I should have it fixed as soon as I finish the syntax highlighting feature. 

Would you like to continue participating in this project? It's getting close to release now and even if you could help as a tester, I'd be very good.

**Comment by Liongold** [comment]
@Denisov21 If you want, I have pushed some very early code (but that should be working) in branch issue-#7. It should include the fix for the issue I mentioned earlier. Do you want to test it?

**Comment by Denisov21** [comment]
@Liongold I will test this weekend on 23/24

**Comment by Denisov21** [comment]
Look good for me!

**Comment by Liongold** [comment]
@Denisov21 Thanks again for this. However, I might rewrite the feature in the future (I'm trying to contribute to the core library). Would you like to be kept informed of this and help test again, please?

**Comment by Denisov21** [comment]
No, now I very busy.

**Comment by Liongold** [comment]
No problem. Thanks your your help until now. Whenever you want, feel free to take a look at the project again.

**Comment by Liongold** [comment]
@Denisov21 I have done some testing on this latest way myself and it worked well for me. Since this is the cleanest I've got, I've decided to merge it. Of course, when you have time, you can come back and do some testing as well. 

However, since the feature is now implemented, then I'll close this issue so that we can advance with the development of this extension. If you want to give feedback, even on this issue, feel free to comment in this again. 

Thanks.
